
PARAMETERS WLEGAJO,WIMPORTE,WMES





WCONCEPTO = 360


IF WMES = 10
  UPDATE NLEGAJO SET OCTUBRE   = WIMPORTE,;
                   NOVIEMBRE = WIMPORTE,;
                   DICIEMBRE = WIMPORTE;
                   WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO
ENDIF


IF WMES = 11
  UPDATE NLEGAJO SET NOVIEMBRE = WIMPORTE,;
                     DICIEMBRE = WIMPORTE;
                     WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO
ENDIF
                   
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 return                  
 
 
 
* UPDATE NLEGAJO SET JULIO = 1666.67;
*WHERE CONCEPTO = 360 .AND. ANO =2017 .AND. JULIO <>0