
PARAMETERS WLEGAJO,WUNIDADES,Varmes

 
WIMPORTE  = 24432
WCONCEPTO = 330

IF Varmes = 10
   UPDATE NLEGAJO SET  OCTUBRE   = ((WIMPORTE/12)*10) *WUNIDADES,;
                   NOVIEMBRE = ((WIMPORTE/12)*11) *WUNIDADES,;
                   DICIEMBRE =  WIMPORTE*WUNIDADES;
                   WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO
 
ENDIF

IF Varmes = 11 
   UPDATE NLEGAJO SET NOVIEMBRE = ((WIMPORTE/12)*11) *WUNIDADES,;
                      DICIEMBRE =  WIMPORTE*WUNIDADES;
                    WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO 
 

ENDIF 
 
 return                  