
PARAMETERS WLEGAJO,tf,WMES

 
WIMPORTE  = 48447
WCONCEPTO = 320
WUNIDADES = 1

linea = "actualizando esposa" + STR(wlegajo,4)
tf.WriteLine(linea)

IF WMES = 10 
   UPDATE NLEGAJO SET  OCTUBRE   = ((WIMPORTE/12)*10),;
                   NOVIEMBRE = ((WIMPORTE/12)*11),;
                   DICIEMBRE =  WIMPORTE*WUNIDADES;
                   WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO
ENDIF


IF WMES = 11
   UPDATE NLEGAJO SET NOVIEMBRE = ((WIMPORTE/12)*11),;
                     DICIEMBRE =  WIMPORTE*WUNIDADES;
                    WHERE LEGAJO = WLEGAJO AND EMPRESA = 1 AND ANO = 2017 AND CONCEPTO = WCONCEPTO 
 
ENDIF 
 
 return                  