SET PATH TO F:\SUELDOS\EMPRE1
SET DELETED ON
CLEAR
SELECT LEGAJO,DESCUENTO FROM 122018 WHERE CONCEPTO = 130 ;
INTO CURSOR RETENCION
SUM DESCUENTO TO VV
?VV
GO top
SCAN
    UPDATE NLEGAJO SET DICIEMBRE = RETENCION.DESCUENTO;
    WHERE EMPRESA=1 .AND. ANO = 2018 .AND. LEGAJO = RETENCION.LEGAJO;
    .AND. CONCEPTO = 605
    ?_tally

ENDSCAN
