SET PATH TO F:\SUELDOS\EMPRE1;c:\CNWGA\FORMS
OPEN DATABASE f:\sueldos\nwga\datos\ganancias SHARED VALIDATE
WNUMES = 4
VVARCHIVO = "42017"
WCAMP = "ABRIL"
SELECT N.LEGAJO,P.NOMBRE,P.FECHABAJA,PS261,&WCAMP AS RET    FROM PERSONAL AS P INNER JOIN NLEGAJO AS N;
ON P.LEGAJO = N.LEGAJO WHERE ANO = 2017 .AND. N.CONCEPTO = 605  ORDER BY RET,N.LEGAJO;
INTO CURSOR INFR READWRITE
SET FILTER TO INFR.RET <>0
SELECT LEGAJO,SUM(DESCUENTO)AS DESCU FROM 42017;
WHERE CONCEPTO = 130 GROUP BY LEGAJO INTO CURSOR AUD
CREATE CURSOR DIFERE(legajo n(4), difere n(12,2), GRET n(12,2), SRET n(12,2)) 
SELECT AUD
SCAN
    SELECT RET FROM INFR WHERE INFR.LEGAJO = AUD.LEGAJO INTO CURSOR EXISTE
    IF INFR.RET <> AUD.DESCU
       Vardif = EXISTE.RET  - AUD.DESCU
       IF Vardif <> 0
         WAIT WINDOW STR(AUD.LEGAJO) + STR( Vardif,12,2)  + "  " + STR(EXISTE.RET,12,2) + " " + STR(AUD.DESCU,12,2)
         INSERT INTO DIFERE (legajo,difere,gret,sret) VALUES (aud.legajo,Vardif,existe.ret,aud.descu)
       ENDIF
    ENDIF   
    
     SELECT AUD


ENDSCAN