SET PATH TO F:\SUELDOS\EMPRE1
SET EXCLUSIVE OFF
archivo = "62018"

SELECT LEGAJO,APORTE FROM &archivo WHERE concepto = 18 INTO CURSOR lsac

SELECT lsac

SCAN
    ? STR(legajo,4)+ " " + STR(aporte,12,2)
    UPDATE NLEGAJO SET JUNIO = LSAC.APORTE;
    WHERE LEGAJO = LSAC.LEGAJO AND EMPRESA = 1 AND ANO = 2018 AND CONCEPTO = 4
    SELECT LSAC

ENDSCAN

CLOSE TABLES 
return