SELECT INFR
SCAN
    SELECT LEGAJO, SUM(APORTE)AS BRUT FROM F:\SUELDOS\EMPRE1\42012 GROUP BY LEGAJO  WHERE LEGAJO = INFR.LEGAJO;
    INTO CURSOR EXISTE
    IF EXISTE.BRUT <> INFR.RET
       WAIT WINDOW "DIFERE :"+ INFR.NOMBRE 
    ENDIF   
    
ENDSCAN

