SET EXCLUSIVE OFF
SET DELETED ON
SET PATH TO F:\SUELDOS\EMPRE1

SELECT LEGAJO,JUNIO  FROM NLEGAJO;
WHERE ANO = 2017  .AND. CONCEPTO =600 .OR. CONCEPTO = 605 .AND. JUNIO <>0 ORDER BY LEGAJO  INTO CURSOR RET ;

SELECT LEGAJO,NOMBRE FROM PERSONAL WHERE ACTIVO = "A" ORDER BY LEGAJO INTO CURSOR LISTA

SELECT L.NOMBRE,RET.JUNIO FROM LISTA  L RIGHT JOIN RET R ON L.LEGAJO = R.LEGAJO ORDER BY R.LEGAJO