SET EXCLUSIVE OFF
SET DATE ITALIAN
SET PATH TO c:\SUElDOS\EMPRE1
SET PROCEDURE TO g:\cnwga\prg\clasfg

SELECT LEGAJO FROM c:\suerut\empre1\PERSONAL;
WHERE ACTIVO = "A" ORDER BY LEGAJO INTO CURSOR  NOMINA
** WMES SON LOS SUELDOS A CARGAR
*** WMACARGAR SON LOS SUELDOS EN GANANCIAS A CARGAR
WMES = 12
WMACARGAR =1

SELECT NOMINA
DO WHILE .NOT. EOF()
    WAIT WINDOW "CARGANDO NOMINA  LEGAJO:" + STR(NOMINA.LEGAJO,4) NOWAIT
    
    OB = CREATEOBJECT("CARGOSUE")
    IF .NOT. USED("gancias")
   		SELECT 0
   		parlegajo  = NOMINA.LEGAJO
   		parempresa = 1  
   		parno     = 2012
   		USE GANCIAS
	ELSE 
   		SELECT GANCIAS
   		parlegajo  = NOMINA.LEGAJO
   		parno     = 2012
   		
   		parempresa = 1
   		REQUERY()
     ENDIF
	SELECT GANCIAS
	OB.LEGAJO  =   NOMINA.LEGAJO
	OB.MES     =   WMACARGAR
	OB.ARCHIVO =  IIF(WMES < 10,LTRIM(STR(WMES,1) + "2011"),LTRIM(STR(WMES,2) + "2011"))  
	*OB.CRGOSUELDO
	OB.PRORRATEO1
	RELEASE OB
	SELECT NOMINA
	IF .NOT. EOF()
	   SKIP
	ELSE
	   EXIT
	ENDIF
ENDDO
CLOSE TABLES
USE	