SET EXCLUSIVE OFF
SET DELETED ON
SET DATE ITALIAN
SET PATH TO F:\SUELDOS\EMPRE1
SET PROCEDURE TO c:\cnwga\prg\clasfg

SELECT LEGAJO FROM PERSONAL;
WHERE ACTIVO = "A" ORDER BY LEGAJO INTO CURSOR  NOMINA
** WMES SON LOS SUELDOS A CARGAR
*** WMACARGAR SON LOS SUELDOS EN GANANCIAS A CARGAR
WMES = 6
WMACARGAR =7

SELECT NOMINA
DO WHILE .NOT. EOF()
    WAIT WINDOW "CARGANDO NOMINA  LEGAJO:" + STR(NOMINA.LEGAJO,4) NOWAIT
    
    OB = CREATEOBJECT("CARGOSUE")
    IF .NOT. USED("gancias")
   		SELECT 0
   		parlegajo  = NOMINA.LEGAJO
   		parempresa = 1  
   		parno     = 2016
   		USE GANCIAS
	ELSE 
   		SELECT GANCIAS
   		parlegajo  = NOMINA.LEGAJO
   		parno     = 2016
   		
   		parempresa = 1
   		REQUERY()
     ENDIF
	SELECT GANCIAS
	OB.LEGAJO  =   NOMINA.LEGAJO
	OB.MES     =   WMACARGAR
	OB.ARCHIVO =  IIF(WMES < 10,LTRIM(STR(WMES,1) + "2016"),LTRIM(STR(WMES,2) + "2016"))  
	*OB.CRGOSUELDO
	OB.PRORRATEO2
	RELEASE OB
	SELECT NOMINA
	IF .NOT. EOF()
	   SKIP
	ELSE
	   EXIT
	ENDIF
ENDDO
CLOSE TABLES
USE	