 SELECT LEGAJO,ABRIL FROM NLEGAJO  WHERE EMPRESA = 1 .AND. CONCEPTO = 600 .AND. ANO = 2012 .AND. ABRIL <>0;
 INTO CURSOR GABRI
 SELECT GABRI 
 BROWSE
 STORE FCREATE('G:\myNamesFile.txt') TO _TEXT
 SCAN
  SELECT chapa,nombre,snacion FROM c:\suerut\empre1\sue3  WHERE snacion <>0 .and. chapa = GABRI.LEGAJO;
  INTO CURSOR EXISTE
  IF (GABRI.ABRIL - EXISTE.SNACION) > 2 
       WAIT WINDOW "NO COINCIDE " + STR(GANANCIAS.CHAPA,4) + " "+ GANANCIAS.NOMBRE
  ENDIF        
  
  
 ENDSCAN
 RETURN