SELECT LEGAJO,(RETEN-SALDO)AS RTG FROM f:\sueldos\nwga\datos\dve ORDER BY LEGAJO INTO CURSOR DEV

SCAN
    UPDATE NLEGAJO SET FEBRERO = DEV.RTG WHERE ANO =2016 .AND. EMPRESA =1 .AND. LEGAJO = DEV.LEGAJO
	SELE DEV
  
ENDSCAN

