SET EXCLUSIVE off

USE f:\sueldos\nwga\datos\dve.dbf SHARED

SCAN FOR SALDO <>0

     INSERT INTO F:\SUELDOS\EMPRE1\22016 (LEGAJO,CONCEPTO,DESCRIP,SINAPORTE,LIQUIDA) VALUES(DVE.LEGAJO,653,"Devol. Gananc",DVE.SALDO,3)
   
ENDSCAN

WAIT WINDOW "PROCESO TERMINADO"