
*SELECT LEGAJO,CONCEPTO, ENERO FROM NLEGAJO WHERE ANO = 2016 .AND. EMPRESA =1 .AND. CONCEPTO = 605;
.AND. ENERO <>0 ORDER BY LEGAJO INTO CURSOR RETEN
*BROWSE
*retimp = 0
*SCAN
*    SELECT reten
*    reteimp = reten.enero
*    *WAIT WINDOW STR(reteimp,10,2)
*    SELECT LEGAJO FROM F:\SUELDOS\NWGA\DATOS\DVE WHERE LEGAJO = RETEN.LEGAJO;
*    INTO CURSOR EXISTE
*    
*    IF EOF()
*        INSERT INTO F:\SUELDOS\NWGA\DATOS\DVE (legajo,concepto,retenido) VALUES (reten.legajo,605,reteimp)
*    ELSE 
*        UPDATE F:\SUELDOS\NWGA\DATOS\DVE SET retenido = reteimp WHERE reten.legajo = dve.legajo
*    ENDIF       
*    reteimp =0
*ENDSCAN

USE F:\SUELDOS\NWGA\DATOS\DVE
SELECT DVE
BROWSE FOR RETENIDO <>0
SCAN FOR RETENIDO <>0
   REPLACE SALDO WITH (RETENIDO - ENERO)
ENDSCAN     
BROWSE FOR RETENIDO <>0


BROWSE FOR SALDO < 0






