SELECT LEGAJO,ABRIL,DICIEMBRE ,ANO FROM NLEGAJO WHERE CONCEPTO = 362 .AND. ANO=2014 .AND. EMPRESA=1 .AND. DICIEMBRE =0;
INTO CURSOR LISAUD
BROWSE

SCAN
   IF DICIEMBRE = 0
      UPDATE NLEGAJO SET ABRIL = 0;
      WHERE LEGAJO = LISAUD.LEGAJO .AND. CONCEPTO = 362 .AND. ANO =2014
   ENDIF    



ENDSCAN