SET EXCLUSIVE OFF
SET DATE ITALIAN
SET CENTURY ON
SET PATH TO F:\FOXPRO2\TRANSPRVA.DAT
LOCAL vvfecha1,vvfecha2 as date
vvfecha1 = CTOD("01-03-2011")
vvfecha2 = CTOD("31-03-2011")
*SELE DE ASIECAB
SELECT FECHA,SECUEN,CUENTA,HABER  FROM f:\foxpro2\transprv.dat\asiedet WHERE fecha >= vvfecha1 .and. fecha <= vvfecha2;
.and. cuenta = "211050050" INTO CURSOR RETEN

*SELECT DE ORDENES DE PAGO
SELECT R.FECHA,R.SECUEN,R.CUENTA,R.HABER,R.NROGEN,O.RESUM,O.IMPORTE,O.CUENTA,O.SECUEN FROM RETEN AS R INNER JOIN OPCAB AS O;
ON O.FECHAEMI = R.FECHA  .AND. R.SECUEN = O.SECUEN